version: "3.9"

services:
  task-service:
    build: .
    container_name: task-service
    ports:
      - "8085:8085"  # host:container
    # env_file:
    #   - .env
    # volumes:
    #   - ./src/main/resources/firebase-service-account.json:/app/firebase-service-account.json
    # restart: unless-stopped